Monorepo, Rebrand to TanStack (#3708)
* rebrand

* move to src

* chore: fix build by re-exporting types explicitly

* chore: run everything through prettier

* chore: bring back linting and compilation tasks

* chore: setup eslint-import-resolver-typescript

it still errors with import/no-unresolved, but I think that's because TS errors as well!

* chore: fix a ton of imports

* chore: down to zero ts errors

* chore: export types separately to make the build work

* chore: down to zero eslint issues 🎉

* chore: try to get tests to work

* chore: make tests work

* fix: use better match sorter primitives

* chore: update workflows

* Update ci.yml

* chore: remove match-sorter dependency

* chore: enable bundle size collection

* chore: update to latest react

* fix(devtools): fix typings of rankItems

not sure if that is correct now...

* chore: fix compilation

* tests: fix tests by removing weird comment that is no longer necessary after upgrading react

* tests: remove incrompehensible tests

I don't know what these tests are doing, but overwriting useEffect is not something that makes sense now that we useSyncExternalStore for data fetching anyways ...

* fix(devtools): fix sorting of queries

rankItem doesn't take keys, so we have to pass the queryHash in directly to rank it

* chore: setup ci pipeline and bundlewatch

* chore: build during pr pipelines

* chore: remove private:true

as requested by CI:
Error: Package undefined in /tmp/98d7e7a6 is set to private, remove package.json#private to publish it

* Revert "chore: remove private:true"

This reverts commit e1b237bf1a19901baf8b55c1d68a5627e27d7660.

* chore: turn off import/no-unresolved in tests

somehow, that fails in CI, and we have typescript protection against unresolved imports anyhow

* fix: turn of import/no-unresolved for all tanstack imports

* fix: regex

* chore: do not run legacy pipelines on PRs

* chore: fix ci check names

* chore: add react-17 dependencies

* chore: split up ci tasks

* fix: building is done via bundlesize reporting

so we don't need to build during testing

* chore: try to make codesandbox ci work

it requires package to be public, but for installing and yarn workspaces, we need it to be private

* fix: apply private: false to all workspaces

* fix: paths to sandboxes

* chore: fix code coverage collection

* chore: change imports from react-query to tanstack/react-query

* docs: update migration docs with the rebrand

* chore: revert codemod changes

prettier destroyed the assertions

* fix(useIsMutating): we need to subscribe to the right cache

this is likely a copy-paste error, and the tests only worked because we render top-down; now, the tests make sure that components are re-rendered because of the subscription itself

* Update README.md

* docs: devtools documentation for tanstack rebrand

* fix builds

* chore: cleanup

Co-authored-by: Dominik Dorfmeister <office@dorfmeister.cc>